[package]
name = "codename_bonfire_server"
version = "0.1.0"
edition = "2021"  # Rust Edition

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "codename_bonfire_server"
path = "source/main.rs"

[dependencies]

# MIT Licence
aes-gcm-siv = "0.11.1"  # Appache 2.0 OR MIT