appenders:
    my_stdout:
        kind: console
        encoder:
            pattern: "{h(\x1b[1m{l}):>16.16}\x1b[0m {m}{n}"
    # my_file_logger:
    #     kind: file
    #     path: "log/my.log"
    #     encoder:
    #         pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
root:
    level: trace
    appenders:
        - my_stdout