# NOTE: Default values are overridden with default values to
# be clear and be resistant against any default change.

# Please view the docs for more details.
# https://rust-lang.github.io/rustfmt/?version=v1.6.0

#// rustfmt meta
# required_version = None
unstable_features = false   # Default

#// Widths
max_width = 80              # modified; Default = 100
array_width = 60            # Default
attr_fn_like_width = 60     # Modified; Default = 60
chain_width = 60            # Default
comment_width = 80          # Default
fn_call_width = 60          # Default
inline_attribute_width = 0  # Default
struct_lit_width = 20       # Modified; Default = 18
struct_variant_width = 60   # Modified; Default = 35

short_array_element_width_threshold = 15 # modified; Default = 10
single_line_if_else_max_width = 50       # Default
single_line_let_else_max_width = 0       # Modified; Default = 0

doc_comment_code_block_width = 80  # Modified; Default = 80
overflow_delimited_expr = false    # Default

fn_args_layout = "Tall"     # Default
fn_params_layout = "Tall"   # Default
fn_single_line = true       # Modified; Default = false

error_on_line_overflow = false # Default
error_on_unformatted   = false # Default

#// Whitespace
blank_lines_lower_bound = 0 # Default
blank_lines_upper_bound = 2 # Modified; Default = 2

#// Bracing
brace_style = "AlwaysNextLine"         # Modified; Default = "SameLineWhere"
control_brace_style = "AlwaysNextLine" # Modified; Default = "AlwaysSameLine"
empty_item_single_line = true          # Default
force_multiline_blocks = false         # Default
match_arm_blocks = true                # Default

#// Misc
color = "Always"                   # Modified; Default = "Auto"
enum_discrim_align_threshold = 0   # Default

# We order imports diffrently.
# We order them: 
#
# <Primary Extention>
# <Internal Imports>
# <Core Rust Modules>
# <External Modules>
#
# With each group seperated by an empty line.
reorder_imports = false            # Modified; Default = true
group_imports = "Preserve"         # Default
reorder_modules = false            # Modified; Default = true

format_code_in_doc_comments = true # Modified; Default = false
format_generated_files = true      # Default
format_macro_matchers = false      # Default
format_macro_bodies = true         # Default
# HTML has a diffrent code style. "*" skips all.
skip_macro_invocations = ["html"]  # Modifed; Default = []
ignore = []                        # Default
format_strings = true              # Modifed; Default = false

# Just because you use windows dosen't mean you get to introduce
# bugs replates to the diffrences between CR-LF and LF
newline_style = "Unix"             # Modified; Default = "Auto"

skip_children = false   # Default

# use_small_heuristics = "" # I don't know what this does.

#// Legability
binop_seperator = "Front"          # Default
combine_control_expr = false       # Modified; Default = true
force_explicit_abi = true          # Default
condense_wildcard_suffixes = false # Default
hex_literal_case = "Lower"         # Modified; Default = Preserve
match_arm_leading_pipes = "Never"  # Default
match_block_trailing_comma = true  # Modified; Default = false
merge_derives = false              # Modified; Default = true
normalize_comments = true          # Modified; Default = false
remove_nested_parens = true        # Default
reorder_impl_items = true          # Modified; Default = false
trailing_comma = "Always"          # Modified, Default = "Vertical"
trailing_semicolon = true          # Modified; Default = false
use_field_init_shorthand = false   # Default
use_try_shorthand = true           # Modified; Default = false

#// Indents and Whitespace
hard_tabs = true              # Modified; Default = false
tab_spaces = 4                # Default
imports_indent = "Visual"     # Modified; Default = "Block"
indent_style = "Block"        # Default
space_after_colon = true      # Default
space_before_colon = false    # Default
spaces_around_ranges = false  # Default
struct_lit_single_line = true # Default
where_single_line = true      # Modified; Default = false
wrap_comments = true          # Modified; Default = false

imports_layout = "HorizontalVertical" # Modified; Default = "Mixed"
struct_field_align_threshold = 40     # Modified; Default = 0
type_punctuation_density = "Wide"     # Default

#// Explicticty
hide_parse_errors = false    # Default
imports_granularity = "Item" # Modified; Default = Preserve
normalize_doc_attributes = true # Modified; Default = false

#// Deprecated Options
# Use the ignore option instead when possible.
disable_all_formatting = false

